### PR TITLE
Updated HL7 logo and changed dimensions to fit

### PR DESCRIPTION
**Pull request by ngfreiter**

### CODE REVIEW

**Review by kjmahalingam — CHANGES_REQUESTED** [review]
Nice! Could you just fix the pixel dimensions to match those in this JIRA ticket, as @markkramerus requests?

https://standardhealthrecord.atlassian.net/browse/CIMPL-26

**Comment by ngfreiter** [comment]
The JIRA ticket ended up being a typo, this version has the correct dimensions.

**Review by kjmahalingam — APPROVED** [review]
Looks good!

**Comment by kjmahalingam** [comment]
@cmoesel This PR is being merged now.

**Pull request merged**
