### PR TITLE
Support for SHR field mappings as needed for fromFHIR

### PR DESCRIPTION
**Pull request by dehall**
Finalizes the SHR field mappings in ElementDefinitions, to be used by from- and toFHIR function definition in the shr-es6-exporter.

### CODE REVIEW

**Comment by cmoesel** [comment]
The actual diff on the one file isn't that huge for 21 commits.  @okeefm and @dehall - how do you feel about me either squashing them all, or rebasing and squashing like commits together (or grouping by author to still give credit where credit is due)?

**Comment by cmoesel** [comment]
NOTE: I think we'll need/want to layer this on top of my `mcode-fixes` branch, so I created a new branch and rebased on `mcode-fixes`.  The new branch is `to_fhir_slicing_rebase_on_mcode_fixes`.  Similarly, we'd need the rebased branch for cli as well: `to_fhir_rebase_on_mcode_fixes`.

It all seems to work well.

If you are OK with that, I'll rebase this branch and force push so the PR gets updated.

**Comment by dehall** [comment]
No objections to either squashing commits or leaving them as-is. 

Rebasing on `mcode-fixes` sounds fine to me, though I haven't been using that branch to this point so I'm not sure what else it changes. I'll give that rebased branch a quick test this morning to confirm.

**Comment by cmoesel** [comment]
I tested with the rebased branch and then compared to the results from the non-rebased branch.  There are differences, but their all related to the shr-fhir-export changes that were taken in -- mainly the _removal_ of some extensions that were actually not needed.

**Comment by cmoesel** [comment]
Closing as this has been replaced by a PR #116, which uses a cleaner rebased branch.

**Pull request closed without merging**
