### PR TITLE
Map to profile bugs

### PR DESCRIPTION
**Pull request by cmoesel**
Fixes various bugs that mainly occur when mapping to profiles.  See individual commits for details.

This works with a corresponding branch / PR on `shr-expand` and the `bp_component_mapping` branch of `shr_spec`.

### CODE REVIEW

**Comment by cmoesel** [comment]
Please do not merge.  Only approve (if appropriate).

**Review by kjmahalingam — COMMENTED** [review]
Code looks good to me, but something seems off because I'm getting these two errors (and only these two).

```
[11:50:30.165Z] ERROR shr: Cannot override code constraint from http://loinc.org|2708-6 to http://loinc.org|59408-5. ERROR_CODE:13048 (module=shr-fhir-export, shrId=vital.OxygenSaturation, target=http://hl7.org/fhir/StructureDefinition/oxygensat, mappingRule="Code maps to code")
[11:50:31.136Z] ERROR shr: Cannot override code constraint from http://loinc.org|9843-4 to http://loinc.org|8287-5. ERROR_CODE:13048 (module=shr-fhir-export, shrId=vital.HeadCircumference, target=http://hl7.org/fhir/StructureDefinition/headcircum, mappingRule="Code maps to code")
```

I ran `node . ../shr_spec/spec` from `shr-cli`.

I had this branch configuration:
```
shr-adl-bmm-export       [master]
shr-cli                  [master]
shr-data-dict-export     [master]
shr-es6-export           [master]
shr-expand               [map_to_profile_bugs]
shr-fhir-export          [map_to_profile_bugs]
shr-grammar              [master]
shr-json-export          [master]
shr-json-javadoc         [master]
shr-json-schema-export   [master]
shr-models               [master]
shr-test-helpers         [master]
shr-text-import          [master]
shr_spec                 [bp_component_mapping]
```

I even ran a `yarn-unlink-all`, `rebuild-all`, and `yarn-link-all` beforehand.

Any ideas what I might be missing?

Additionally, @cmoesel, would you like two reviews? One from myself and one from @ngfreiter?

**Comment by cmoesel** [comment]
@kjmahalingam -- I'll give it a try on my end.  I'm realizing now that I did most (or all?) of my testing using the `ig-mcode-r4-config.json` -- so the errors you noted may be in elements filtered out of that config.  I'll try with `ig-all-r4-config.json`.

Those errors, by the way, are likely a sign that the PR is *working*, as it means we're properly detecting existing fixed codes in the profile we map to, and issuing an error if we try to fix a *different* code than the one already there.

As for number of approvals, I mainly just wanted @ngfreiter to be aware of the PRs (as part of his continuing education), but I only need one approval.

**Comment by cmoesel** [comment]
I've confirmed that I also receive those errors and that those errors are valid.  The CLI is doing its job.  I'll talk to the spec team about fixing those codes.

**Review by kjmahalingam — APPROVED** [review]

**Pull request merged**
