### PR TITLE
Fhir R4

### PR DESCRIPTION
**Pull request by cmoesel**
Support for FHIR R4 plus other bug fixes that came up along the way.

Test this against @markkramerus's shr_spec branch: `dev-R4map-mk`

He now has configs for all supported FHIR versions:
* `ig-all-dstu2-config.json`
* `ig-all-stu3-config.json`
* `ig-all-r4-config.json`

Current a DRAFT pull request because I need to bump the version to non-beta once you approve and before I merge.

### CODE REVIEW

**Comment by kjmahalingam** [comment]
Branch setup:
```
shr-adl-bmm-export       [master]
shr-cli                  [fhir-r4]
shr-es6-export           [fhir-r4]
shr-expand               [master]
shr-fhir-export          [fhir-r4]
shr-grammar              [master]
shr-json-export          [master]
shr-json-javadoc         [master]
shr-json-schema-export   [master]
shr-models               [master]
shr-test-helpers         [master]
shr-text-import          [master]
shr_spec                 [dev-R4map-mk]
```
Running on DSTU2 config:
```
Elapsed time: 101.530s
1314 errors (shr-es6-export)
326 warnings (shr-text-input, shr-json-export, shr-fhir-export, shr-json-schema-export)
```
Running on STU3 config:
```
Elapsed time: 138.608s
1541 errors (shr-es6-export)
192 warnings (shr-text-input, shr-json-export, shr-fhir-export, shr-json-schema-export)
```
Running on R4 config:
```
Elapsed time: 127.799s
1370 errors (shr-es6-export)
170 warnings (shr-text-input, shr-json-export, shr-fhir-export, shr-json-schema-export)
```
Assuming that there are still known errors in ES6 export, the rest works without error.
Tests pass, with some marked as pending, but no failures.

**Review by kjmahalingam — APPROVED** [review]

**Comment by cmoesel** [comment]
Thanks @kjmahalingam.  Just to be sure we didn't drastically _increase_ the errors, I also ran the DSTU2 and STU3 configs against the latest stable release `5.17.4`.  The number of ES6 errors remained the same in both cases and the number of warnings actually fell (likely due to some fixed bugs).

Running 5.17.4 stable release on DSTU2 config:
```
Elapsed time: 96.175s
1314 errors (shr-es6-export)
297 warnings (shr-text-input, shr-json-export, shr-fhir-export, shr-json-schema-export)
```

Running 5.17.4 stable release on STU3 config:
```
Elapsed time: 110.191s
1541 errors (shr-es6-export)
175 warnings (shr-text-input, shr-json-export, shr-fhir-export, shr-json-schema-export)
```

So...  knowing that you also manually reviewed the code, I think we're good.

**Comment by kjmahalingam** [comment]
Perfect, then I'm on board with that!

**Comment by cmoesel** [comment]
@kjmahalingam -- looking for your feedback here.  There are a lot of commits.  Do you think the commit log is useful or should I squish them?  I think we have 3 possible approaches:
* leave as-is
* squish into one big commit
* rebase into 6 commits (one commit per beta release containing all the changes for that beta)

**Comment by kjmahalingam** [comment]
@cmoesel I'm partial to the approach with rebasing into 6 commits, since I agree that it's a bit large in terms of number of commits, but having some granularity in the commit logs would be useful.

**Pull request merged**
