### PR TITLE
Markdown, Examples, and Slicing.  Oh My!

### PR DESCRIPTION
**Pull request by cmoesel**
This PR incorporates several requested changes from another project using CIMPL.  They are:

- Render markdown descriptions in the IG's profile, logical model, value set, and code system listing pages.
- Support optional examples in the IG
- Fix an issue that prevented slicing from working in some cases

To add examples to your IG:
- create a `fhir_examples` folder in the same folder as your config and txt files
- put JSON-formatted examples in the folder.  Make sure they specify the meta.profile URL so the IG knows which profile to associate them with

To test markdown and the slicing issue, run the CLI against `/spec` in the following project:
https://github.com/cmoesel/fhir-death-record/archive/fix_slice_map.zip

Without the fixes, the CLI will emit an error.  With the fixes, it won't.

### CODE REVIEW

**Comment by Abhijay** [comment]
Generated the IG and tested the markdown and slicing fixes, they seem to be working as intended +1
Code review also checks out +1

Are there any pre-existing `fhir_examples` examples to test against?

**Review by Abhijay — COMMENTED** [review]
Generated the IG and tested the markdown and slicing fixes, they seem to be working as intended +1
Code review also checks out +1

Are there any pre-existing `fhir_examples` examples to test against?

**Comment by cmoesel** [comment]
To test examples, run the CLI against `/spec` in the following project:
https://github.com/cmoesel/fhir-death-record/archive/examples.zip

Then run the IG publisher.  After that, if you go to _Profiles -> ActualOrPresumedDateOfDeath_, you should see a new "Examples" tab.  Click it and look at the "dod" example.

You should also see that other profiles _don't_ have the "Examples" tab.

**Comment by Abhijay** [comment]
Running the ig on the spec you provided, I don't see an 'example' tab. Looking at the `fhir-death-record-example` files, I couldn't find an `fhir_examples` folder (additionally it's virtually identical to the `fhir-death-record-master` folder except for one mapping).

Perhaps you might've forgotten to push up some code in your example spec?

**Comment by cmoesel** [comment]
Oh man.  You're right.  I forgot to actually commit the examples.  I'm very sorry for wasting your time.  It is fixed now!

**Review by Abhijay — APPROVED** [review]
Examples look good. Ready to merge in.

**Pull request merged**
